pipeline {
    agent any
    
    stages {
        stage('cloning') {
            steps {
                sh '''
                git clone https://github.com/krish80552/Jenkins.git
                '''
            }
        }
        
        stage('generating') {
            steps {
                sh '''
                cd basic_code
                mvn clean install
                '''
            }
        }
        
        stage('uploading') {
            steps {
                sh '''
                aws s3 cp basic_code/webapp/target/webapp.war s3://jandevopsbucket/
                '''
            }
        }
          
    }
    post { 
        always { 
            cleanWs()
        }
    }
}
